global:
  scrape_interval:     15s

scrape_configs:
  - job_name: 'spring-actuator-scrape'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.0.6:8080']
    basic_auth:
      username: 'ss@gmail.com'
      password: 'abc123ABC'

